### ISSUE TITLE
Coarray debug & function check

### ISSUE THREAD

**Issue by ghost** [wtdailey/HASTE#13]
Need to configure build environment and scripts to link appropriate libraries for coarray execution.  Source compiles with coarray flags (-fcoarray=lib) and directives, but build environment presently cannot locate the coarray library (-lcaf_mpi) for the linking step.  Serial (non-coarray) implementation builds successfully, so coding is able to continue, but coarray functionality needs to be fixed or verified.

**Comment by HATSwg** [comment]
Development environment needed some file reinstalled... This may have been a strictly local issue.  Need to check if this is still an issue.

**Comment by HATSwg** [comment]
Still and issue: tried in another environment.

**Comment by HATSwg** [comment]
Moved to the 1.1 milestone since this is not critical to a running version of the code.

**Comment by wtdailey** [comment]
Fixes are development environment specific, so maintaining a global guarantee of coarray functionality is not reasonable.  Closing.
