### ISSUE TITLE
On-the-Fly Reconstruction of Resonance Cross Sections

### ISSUE THREAD

**Issue by ghost** [wtdailey/HASTE#3]
Need to implement true in-place on-the-fly (OTF) reconstruction of resonance cross sections.  This will replace patched implementation in n_Cross_Sections.f90 that uses preprocessed linearly-interpolable cross section files.  Resources data files will also change in content and structure to support direct use of ENDF data instead of preprocessed data.

**Comment by HATSwg** [comment]
Need solid reference (or previous code/implementation) to use as cook-book for this.  Direct implementation out of ENDF formats manual will be uphill battle:  Faster (and likely more robust) approach is reuse of previous procedures).

**Comment by HATSwg** [comment]
Fine.  I'll do it myself.

**Comment by HATSwg** [comment]
https://github.com/HATSwg/HATS/blob/85d68082c7fe46927d08c5adbcea9868deedd79f/source/parts/n_Cross_Sections.f90#L1994
and
https://github.com/HATSwg/HATS/blob/85d68082c7fe46927d08c5adbcea9868deedd79f/source/parts/n_Cross_Sections.f90#L2073

Are the locations at which the arithmetic for resonance cross section reconstruction is required.  The implementation is a little muddled by the interface with the data structure (derived types and such), but that can change to accommodate the final routine.  The code present in these routines currently is a previous attempt by me to piece together the fragmented documentation on resonance reconstruction.  It is unverified and untested.
